Hospital/Models/Doctor.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Hospital.Models
{
    public class Doctor
    {
        [Key]
        public int ID_Doctor { get; set; }
        public int Turno { get; set; }

        [ForeignKey("Usuario")]
        public string ID_Usuario{ get; set; }

        public Usuario Usuario { get; set; }

        public string Cedula { get; set; }

        public List<Horario_Doctor> Horario_Doctor { get; set; }

        public List<Receta_Medica> Receta_Medica { get; set; }

        [ForeignKey("Especialidad")]
        public int? ID_Especialidad { get; set; }

        public Especialidad Especialidad { get; set; }

        public List<Cita> Cita { get; set; }

        [ForeignKey("Consultorio")]
        public int? ID_Consultorio { get; set; }

        public Consultorio? Consultorio { get; set; }
    }
}

Hospital/Controllers/CitasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Hospital.Data;
using Hospital.Models;
using Hospital.Migrations;
using Humanizer;

namespace Hospital.Controllers
{
    public class CitasController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CitasController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Citas
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Cita
                .Include(c => c.Doctor)
                .Include(c => c.Paciente)
                .Include(c => c.Receta_Medica)
                .Include(c => c.Paciente.Usuario)
                .Include(c => c.Doctor.Usuario)
                .Include(c => c.Doctor.Especialidad)
                .Include(c => c.Doctor.Consultorio);
            return View(await applicationDbContext.ToListAsync());
        }

        public async Task<IActionResult> IndexDoctor(int id)
        {
            var applicationDbContext = _context.Cita
                .Include(c => c.Doctor)
                .Include(c => c.Paciente)
                .Include(c => c.Receta_Medica)
                .Include(c => c.Paciente.Usuario)
                .Include(c => c.Doctor.Usuario)
                .Include(c => c.Doctor.Especialidad)
                .Include(c => c.Doctor.Consultorio)
                .Where(u => u.ID_Doctor == id);
            return View(await applicationDbContext.ToListAsync());
        }

        public async Task<IActionResult> IndexPaciente(int id)
        {
            var applicationDbContext = _context.Cita
                .Include(c => c.Doctor)
                .Include(c => c.Paciente)
                .Include(c => c.Receta_Medica)
                .Include(c => c.Paciente.Usuario)
                .Include(c => c.Doctor.Usuario)
                .Include(c => c.Doctor.Especialidad)
                .Include(c => c.Doctor.Consultorio)
                .Where(u => u.ID_Paciente == id);
            return View(await applicationDbContext.ToListAsync());
        }
        // GET: Citas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Cita == null)
            {
                return NotFound();
            }

            var cita = await _context.Cita
                .Include(c => c.Doctor)
                .Include(c => c.Paciente)
                .Include(c => c.Doctor.Usuario)
                .Include(c => c.Paciente.Usuario)
                .Include(c => c.Receta_Medica)
                 .Include(c => c.Doctor.Especialidad)
                .Include(c => c.Doctor.Consultorio)
                .FirstOrDefaultAsync(m => m.ID_Cita == id);
            if (cita == null)
            {
                return NotFound();
            }

            return View(cita);
        }

        // GET: Citas/Create
        public IActionResult Create()
        {
            var doctor = _context.Doctor.Include("Usuario").ToList();
            var paciente = _context.Paciente.Include("Usuario").ToList();
            ViewBag.Doctor = doctor;
            ViewBag.Paciente = paciente;
            ViewData["ID_Doctor"] = new SelectList(_context.Doctor, "ID_Doctor", "ID_Doctor");
            ViewData["ID_Paciente"] = new SelectList(_context.Paciente, "ID_Paciente", "ID_Paciente");
            ViewData["ID_Receta_Medica"] = new SelectList(_context.Receta_Medica, "ID_Receta", "Especificaciones");
            return View();
        }

        // POST: Citas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID_Cita,Pagado,Día,Hora,ID_Doctor,ID_Receta_Medica,ID_Paciente")] Cita cita)
        {
            var disponibilidad = _context.Cita.Where(u => u.Día == cita.Día)
                                 .Where(o => o.Hora.Hour == cita.Hora.Hour)
                                 .Where(u => u.ID_Doctor == cita.ID_Doctor)
                                .ToList();
            // var doctdisp = _context.Cita;
            var doctor = _context.Doctor.Include("Usuario").ToList();
            var paciente = _context.Paciente.Include("Usuario").ToList();
            ViewBag.Doctor = doctor;
            ViewBag.Paciente = paciente;
            ViewData["ID_Doctor"] = new SelectList(_context.Doctor, "ID_Doctor", "ID_Doctor", cita.ID_Doctor);
            ViewData["ID_Paciente"] = new SelectList(_context.Paciente, "ID_Paciente", "ID_Paciente", cita.ID_Paciente);
//ViewData["ID_Receta_Medica"] = new SelectList(_context.Receta_Medica, "ID_Receta", "Especificaciones", cita.ID_Receta_Medica);
            DateTime hoy = DateTime.Now;
            var validacion = (cita.Día - hoy).Days;
             if ((hoy - cita.Día).Days > 90)
            {
                ViewBag.MuchosDias = "Escoja una fecha mas reciente";
                return View();
            }
            
           if(cita.Día < hoy)
            {
                ViewBag.ErrorDia = "No se pueden poner fechas anteriores";
               // ViewBag.ErrorMensaje = "Horario ocupado";
                
                return View();
            }
            if (disponibilidad.Count != 0)
            {
                ViewBag.ErrorMensaje = "Horario ocupado";
                // var doctor = _context.Doctor.Include("Usuario").ToList();
                //var paciente = _context.Paciente.Include("Usuario").ToList();
                //ViewBag.Doctor = doctor;
                //ViewBag.Paciente = paciente;
                //ViewData["ID_Doctor"] = new SelectList(_context.Doctor, "ID_Doctor", "ID_Doctor", cita.ID_Doctor);
                //ViewData["ID_Paciente"] = new SelectList(_context.Paciente, "ID_Paciente", "ID_Paciente", cita.ID_Paciente);
                //ViewData["ID_Receta_Medica"] = new SelectList(_context.Receta_Medica, "ID_Receta", "Especificaciones", cita.ID_Receta_Medica);
                return View();
            }
            if (ModelState.IsValid)
            {
                _context.Add(cita);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Details), new { id = cita.ID_Cita });
            }
           
          
           
            return View(cita);
        }

       
        // GET: Citas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Cita == null)
            {
                return NotFound();
            }

            var cita = await _context.Cita.FindAsync(id);
            if (cita == null)
            {
                return NotFound();
            }
            ViewData["ID_Doctor"] = new SelectList(_context.Doctor, "ID_Doctor", "ID_Doctor", cita.ID_Doctor);
            ViewData["ID_Paciente"] = new SelectList(_context.Paciente, "ID_Paciente", "ID_Paciente", cita.ID_Paciente);
        //    ViewData["ID_Receta_Medica"] = new SelectList(_context.Receta_Medica, "ID_Receta", "Especificaciones", cita.ID_Receta_Medica);
            return View(cita);
        }

        // POST: Citas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID_Cita,Pagado,Día,Hora,ID_Doctor,ID_Receta_Medica,ID_Paciente")] Cita cita)
        {
            ViewData["ID_Doctor"] = new SelectList(_context.Doctor, "ID_Doctor", "ID_Doctor", cita.ID_Doctor);
            ViewData["ID_Paciente"] = new SelectList(_context.Paciente, "ID_Paciente", "ID_Paciente", cita.ID_Paciente);
           // ViewData["ID_Receta_Medica"] = new SelectList(_context.Receta_Medica, "ID_Receta", "Especificaciones", cita.ID_Receta_Medica);
            var disponibilidad = _context.Cita.Where(u => u.Día == cita.Día)
                                .Where(o => o.Hora.Hour == cita.Hora.Hour)
                                .Where(u => u.ID_Doctor == cita.ID_Doctor)
                               .ToList();
            DateTime hoy = DateTime.Now;
            if ((cita.Día - hoy).Days > 90)
            {
                ViewBag.MuchosDias = "Escoja una fecha mas reciente";
                return View();
            }

            if (cita.Día < hoy)
            {
                ViewBag.ErrorDia = "No se pueden poner fechas anteriores";
                // ViewBag.ErrorMensaje = "Horario ocupado";

                return View();
            }
            if (disponibilidad.Count != 0)
            {
                ViewBag.ErrorMensaje = "Horario ocupado";
                // var doctor = _context.Doctor.Include("Usuario").ToList();
                //var paciente = _context.Paciente.Include("Usuario").ToList();
                //ViewBag.Doctor = doctor;
                //ViewBag.Paciente = paciente;
                //ViewData["ID_Doctor"] = new SelectList(_context.Doctor, "ID_Doctor", "ID_Doctor", cita.ID_Doctor);
                //ViewData["ID_Paciente"] = new SelectList(_context.Paciente, "ID_Paciente", "ID_Paciente", cita.ID_Paciente);
                //ViewData["ID_Receta_Medica"] = new SelectList(_context.Receta_Medica, "ID_Receta", "Especificaciones", cita.ID_Receta_Medica);
                return View();
            }
            if (id != cita.ID_Cita)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(cita);

Hospital/Views/Doctors/Create.cshtml
@model Hospital.ViewModel.UsuarioDoctoVM

@{
    ViewData["Title"] = "Create";
    string error = ViewBag.Error as string;
}

<h1>Create</h1>

<h4>Doctor</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="usuario.Telefono" class="control-label"></label>
                <input asp-for="usuario.Telefono" class="form-control" />
                <span asp-validation-for="usuario.Telefono" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
           
            <div class="form-group">
                <label asp-for="CURP" class="control-label"></label>
                <input asp-for="CURP" class="form-control" />
                <span asp-validation-for="CURP" class="text-danger"></span>
            </div>
            @if (!string.IsNullOrEmpty(error))
            {
                <div class="alert alert-danger">
                    @error
                </div>
            }
            <div class="form-group">
                <label asp-for="Cedula" class="control-label"></label>
                <input asp-for="Cedula" class="form-control" />
                <span asp-validation-for="CURP" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RegisterModel.Input.ConfirmPassword" class="control-label"></label>
                <input asp-for="RegisterModel.Input.ConfirmPassword" class="form-control" />
                <span asp-validation-for="RegisterModel.Input.ConfirmPassword" class="text-danger"></span>
            </div>
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Consultorio" class="control-label"></label>
                <select asp-for="Consultorio" class="form-control"> 
                    <option>Seleccionar</option>
                    @foreach (var consultorio in @ViewBag.Consultorio)
                    {
                        <option value="@consultorio.ID_Consultorio">@consultorio.Nombre</option>
                    }
                </select>
                <span asp-validation-for="Consultorio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Turno" class="control-label"></label>
                <input asp-for="Turno" class="form-control" />
                <span asp-validation-for="Turno" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Especialidad" class="control-label"></label>
                <select asp-for="Especialidad" class="form-control">
                    <option>Seleccionar</option>
                    @foreach(var Especialidad in ViewBag.Especialidad)
                    {
                        <option value="@Especialidad.ID_Especialidad">@Especialidad.Nombre</option>
                    }
                </select>
                <span asp-validation-for="Especialidad" class="text-danger"></span>
            </div>
          
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Hospital/Views/Doctors/Delete.cshtml
@model Hospital.Models.Doctor

@{
    ViewData["Title"] = "Delete";
    string error = ViewBag.Error as string;
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Doctor</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Consultorio)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Consultorio)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Turno)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Turno)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Especialidad)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Especialidad)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Usuario)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Usuario.Id)
        </dd>
    </dl>

    @if (!string.IsNullOrEmpty(error))
    {
        <div class="alert alert-danger">
            @error
        </div>
    }
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID_Doctor" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Hospital/Views/Doctors/Details.cshtml
@model Hospital.Models.Doctor

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Doctor</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Consultorio)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Consultorio)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Turno)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Turno)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Especialidad)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Especialidad)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Usuario)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Usuario.Id)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.ID_Doctor">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Hospital/Views/Doctors/Edit.cshtml
@model Hospital.Models.Doctor

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Doctor</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID_Doctor" />
            <div class="form-group">
                <label asp-for="Consultorio" class="control-label"></label>
                <select asp-for="Consultorio" class="form-control">
                    <option>Seleccionar</option>
                    @foreach (var consultorio in ViewBag.Consultorio)
                    {
                        <option value="@consultorio.ID_Consultorio">@consultorio.Nombre</option>
                    }
                </select>
                <span asp-validation-for="Consultorio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Turno" class="control-label"></label>
                <input asp-for="Turno" class="form-control" />
                <span asp-validation-for="Turno" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Especialidad" class="control-label"></label>
                <input asp-for="Especialidad" class="form-control" />
                <span asp-validation-for="Especialidad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ID_Usuario" class="control-label"></label>
                <select asp-for="ID_Usuario" class="form-control" asp-items="ViewBag.ID_Usuario"></select>
                <span asp-validation-for="ID_Usuario" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Hospital/Views/Doctors/Index.cshtml
@model IEnumerable<Hospital.Models.Doctor>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>

            <th>
                @Html.DisplayNameFor(model => model.Turno)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Especialidad)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Usuario.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Consultorio)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cedula)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
           
            <td>
                @Html.DisplayFor(modelItem => item.Turno)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Especialidad.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Usuario.Nombre)
            </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Consultorio.Nombre)
                </td>
             <td>
                @Html.DisplayFor(modelItem => item.Cedula)
            </td>
               
           
            <td>
                <a asp-action="Edit" asp-route-id="@item.ID_Doctor">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.ID_Doctor">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.ID_Doctor">Delete</a> |
                <a asp-area="" asp-route-id="@item.ID_Doctor" asp-controller="Citas" asp-action="IndexDoctor">Ver Citas</a> | 
                <a asp-area="" asp-route-id="@item.ID_Doctor" asp-controller="Receta_Medica" asp-action="IndexDoctor">Ver Recetas</a>
            </td>
        </tr>
}
    </tbody>
</table>