Hospital/Models/Cita.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Hospital.Models
{
    public class Cita
    {
        [Key]
        public int ID_Cita { get; set; }
        public bool Pagado { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime Día { get; set; }

        [DataType(DataType.Time)]
        [DisplayFormat(DataFormatString = "{0:HH\\:mm}", ApplyFormatInEditMode = true)]
        public DateTime Hora { get; set; }

        [ForeignKey("Doctor")]
        public int ID_Doctor { get; set; }

        public Doctor? Doctor { get; set; }

     

        public Receta_Medica? Receta_Medica { get; set; }

        [ForeignKey("Paciente")]
        public int ID_Paciente { get; set; }

        public Paciente? Paciente { get; set; }
        public Factura? Factura { get; set; }
    }

}

Hospital/Controllers/Receta_MedicaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Hospital.Data;
using Hospital.Models;

namespace Hospital.Controllers
{
    public class Receta_MedicaController : Controller
    {
        private readonly ApplicationDbContext _context;

        public Receta_MedicaController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Receta_Medica
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Receta_Medica
                .Include(r => r.Cita)
                .Include(r => r.Doctor)
                 .Include(r => r.Doctor.Usuario)
                .Include(r => r.Medicina);
            return View(await applicationDbContext.ToListAsync());
        }

        public async Task<IActionResult> IndexDoctor(int id)
        {
            var applicationDbContext = _context.Receta_Medica
                .Include(r => r.Cita)
                .Include(r => r.Doctor)
                 .Include(r => r.Doctor.Usuario)
                .Include(r => r.Medicina)
                .Where(u => u.ID_Doctor == id);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Receta_Medica/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Receta_Medica == null)
            {
                return NotFound();
            }

            var receta_Medica = await _context.Receta_Medica
                .Include(r => r.Cita)
                .Include(r => r.Doctor)
                .Include(r => r.Medicina)
                .FirstOrDefaultAsync(m => m.ID_Receta == id);
            if (receta_Medica == null)
            {
                return NotFound();
            }

            return View(receta_Medica);
        }

        // GET: Receta_Medica/Create
        public IActionResult Create()
        {
            ViewData["ID_Cita"] = new SelectList(_context.Cita, "ID_Cita", "ID_Cita");
            ViewData["ID_Doctor"] = new SelectList(_context.Doctor, "ID_Doctor", "ID_Doctor");
            ViewData["ID_Medicina"] = new SelectList(_context.Medicina, "ID_Medicina", "Nombre");
            return View();
        }

        public IActionResult CreateCita(int id)
        {
            ViewBag.Id = id;
            ViewData["ID_Cita"] = new SelectList(_context.Cita.Where(u => u.ID_Cita == id), "ID_Cita", "ID_Cita");
            ViewData["ID_Doctor"] = new SelectList(_context.Doctor, "ID_Doctor", "ID_Doctor");
            ViewData["ID_Medicina"] = new SelectList(_context.Medicina, "ID_Medicina", "Nombre");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateCita([Bind("ID_Receta,Diagnostico,Tratamiento,Duracion,Especificaciones,ID_Doctor,ID_Medicina,ID_Cita")] Receta_Medica receta_Medica)
        {
            var doctor = _context.Cita.Where(u => u.ID_Cita == receta_Medica.ID_Cita).FirstOrDefault();
            Receta_Medica receta = new Receta_Medica()
            {
                Diagnostico = receta_Medica.Diagnostico,
                Fecha = DateTime.Now,
                Tratamiento = receta_Medica.Tratamiento,
                Duracion = receta_Medica.Duracion,
                Especificaciones = receta_Medica.Especificaciones,
                ID_Doctor = doctor.ID_Doctor,
                ID_Medicina = receta_Medica.ID_Medicina,
                ID_Cita = receta_Medica.ID_Cita
            };
            if (ModelState.IsValid)
            {
                _context.Add(receta);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ID_Cita"] = new SelectList(_context.Cita, "ID_Cita", "ID_Cita", receta_Medica.ID_Cita);
            ViewData["ID_Doctor"] = new SelectList(_context.Doctor, "ID_Doctor", "ID_Doctor", receta_Medica.ID_Doctor);
            ViewData["ID_Medicina"] = new SelectList(_context.Medicina, "ID_Medicina", "Nombre", receta_Medica.ID_Medicina);
            return View(receta_Medica);
        }

        // POST: Receta_Medica/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID_Receta,Diagnostico,Tratamiento,Duracion,Especificaciones,ID_Doctor,ID_Medicina,ID_Cita")] Receta_Medica receta_Medica)
        {
            var doctor = _context.Cita.Where(u => u.ID_Cita == receta_Medica.ID_Cita).FirstOrDefault();
            Receta_Medica receta = new Receta_Medica()
            {
                Diagnostico = receta_Medica.Diagnostico,
                Fecha = DateTime.Now,
                Tratamiento = receta_Medica.Tratamiento,
                Duracion = receta_Medica.Duracion,
                Especificaciones = receta_Medica.Especificaciones,
                ID_Doctor = doctor.ID_Doctor,
                ID_Medicina = receta_Medica.ID_Medicina,
                ID_Cita = receta_Medica.ID_Cita
            };
            if (ModelState.IsValid)
            {
                _context.Add(receta);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ID_Cita"] = new SelectList(_context.Cita, "ID_Cita", "ID_Cita", receta_Medica.ID_Cita);
            ViewData["ID_Doctor"] = new SelectList(_context.Doctor, "ID_Doctor", "ID_Doctor", receta_Medica.ID_Doctor);
            ViewData["ID_Medicina"] = new SelectList(_context.Medicina, "ID_Medicina", "Nombre", receta_Medica.ID_Medicina);
            return View(receta_Medica);
        }

        // GET: Receta_Medica/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Receta_Medica == null)
            {
                return NotFound();
            }

            var receta_Medica = await _context.Receta_Medica.FindAsync(id);
            if (receta_Medica == null)
            {
                return NotFound();
            }
            ViewData["ID_Cita"] = new SelectList(_context.Cita, "ID_Cita", "ID_Cita", receta_Medica.ID_Cita);
            ViewData["ID_Doctor"] = new SelectList(_context.Doctor, "ID_Doctor", "ID_Doctor", receta_Medica.ID_Doctor);
            ViewData["ID_Medicina"] = new SelectList(_context.Medicina, "ID_Medicina", "Nombre", receta_Medica.ID_Medicina);
            return View(receta_Medica);
        }

        // POST: Receta_Medica/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID_Receta,Diagnostico,Fecha,Tratamiento,Duracion,Especificaciones,ID_Doctor,ID_Medicina,ID_Cita")] Receta_Medica receta_Medica)
        {
            if (id != receta_Medica.ID_Receta)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(receta_Medica);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!Receta_MedicaExists(receta_Medica.ID_Receta))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ID_Cita"] = new SelectList(_context.Cita, "ID_Cita", "ID_Cita", receta_Medica.ID_Cita);
            ViewData["ID_Doctor"] = new SelectList(_context.Doctor, "ID_Doctor", "ID_Doctor", receta_Medica.ID_Doctor);
            ViewData["ID_Medicina"] = new SelectList(_context.Medicina, "ID_Medicina", "Nombre", receta_Medica.ID_Medicina);
            return View(receta_Medica);
        }

        // GET: Receta_Medica/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Receta_Medica == null)
            {
                return NotFound();
            }

            var receta_Medica = await _context.Receta_Medica
                .Include(r => r.Cita)
                .Include(r => r.Doctor)
                .Include(r => r.Medicina)
                .FirstOrDefaultAsync(m => m.ID_Receta == id);
            if (receta_Medica == null)
            {
                return NotFound();
            }

            return View(receta_Medica);
        }

        // POST: Receta_Medica/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Receta_Medica == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Receta_Medica'  is null.");
            }
            var receta_Medica = await _context.Receta_Medica.FindAsync(id);
            if (receta_Medica != null)
            {
                _context.Receta_Medica.Remove(receta_Medica);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool Receta_MedicaExists(int id)
        {
          return (_context.Receta_Medica?.Any(e => e.ID_Receta == id)).GetValueOrDefault();
        }
    }
}

Hospital/Views/Citas/CitaGenerada.cshtml
@model Hospital.Models.Cita

@{
    ViewData["Title"] = "CitaGenerada";
}

<h1>CitaGenerada</h1>

<div>
    <h4>Cita</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Pagado)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Pagado)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Día)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Día)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Hora)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Hora)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Doctor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Doctor.ID_Doctor)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Receta_Medica)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Receta_Medica)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Paciente)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Paciente.ID_Paciente)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.ID_Cita">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Hospital/Views/Citas/Create.cshtml
@model Hospital.Models.Cita

@{
    ViewData["Title"] = "Create";
}

@{
    string errorMensaje = ViewBag.ErrorMensaje as string;
    string diaerrorneo = ViewBag.ErrorDia as string;
    string muchodias = ViewBag.MuchosDias as string;
}
<h1>Create</h1>

<h4>Cita</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Pagado" /> @Html.DisplayNameFor(model => model.Pagado)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="Día" class="control-label"></label>
                <input asp-for="Día" class="form-control" />
                <span asp-validation-for="Día" class="text-danger"></span>
            </div>
            @if (!string.IsNullOrEmpty(diaerrorneo))
            {
                <div class="alert alert-danger">
                    @diaerrorneo
                </div>
            }
            @if (!string.IsNullOrEmpty(muchodias))
            {
                <div class="alert alert-danger">
                    @muchodias
                </div>
            }
            <div class="form-group">
                <label asp-for="Hora" class="control-label"></label>
                <input asp-for="Hora" class="form-control  />
                <span asp-validation-for="Hora" class="text-danger"></span>
            </div>
            @if (!string.IsNullOrEmpty(errorMensaje))
            {
                <div class="alert alert-danger">
                    @errorMensaje
                </div>
            }
            <div class="form-group">
                <label asp-for="ID_Doctor" class="control-label"></label>
                <select asp-for="ID_Doctor" class ="form-control">
                    <option>Seleccionar</option>
                    @foreach(var doctor in ViewBag.Doctor)
                    {
                        <option value="@doctor.ID_Doctor">@doctor.Usuario.Nombre</option>
                    }
                </select>
            </div>
           
            <div class="form-group">
                <label asp-for="ID_Paciente" class="control-label"></label>
                <select asp-for="ID_Paciente" class ="form-control">
                    <option>Seleccionar</option>
                    @foreach(var paciente in ViewBag.Paciente)
                    {
                        <option value="@paciente.ID_Paciente">@paciente.Usuario.Nombre</option>
                    }
                </select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Hospital/Views/Citas/Delete.cshtml
@model Hospital.Models.Cita

@{
    ViewData["Title"] = "Delete";

    string error = ViewBag.ErrorHora as string;
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Cita</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Pagado)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Pagado)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Día)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Día)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Hora)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Hora)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Doctor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Doctor.ID_Doctor)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Receta_Medica)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Receta_Medica)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Paciente)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Paciente.ID_Paciente)
        </dd>
    </dl>
    @if (!string.IsNullOrEmpty(error))
    {
        <div class="alert alert-danger">
            @error
        </div>
    }
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID_Cita" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Hospital/Views/Citas/Details.cshtml
@model Hospital.Models.Cita

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Cita</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ID_Cita)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ID_Cita)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Paciente)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Paciente.Usuario.Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Pagado)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Pagado)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Día)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Día)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Hora)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Hora)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Doctor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Doctor.Usuario.Nombre)
        </dd>
        <dt class="col-sm-2">
          Especialidad
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Doctor.Especialidad.Nombre)
        </dd>
        <dt class="col-sm-2">
            Consultorio
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Doctor.Consultorio.Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Receta_Medica)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Receta_Medica.Especificaciones)
        </dd>
       
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.ID_Cita">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Hospital/Views/Citas/Edit.cshtml
@model Hospital.Models.Cita

@{
    ViewData["Title"] = "Edit";
}

@{
    string errorMensaje = ViewBag.ErrorMensaje as string;
    string diaerrorneo = ViewBag.ErrorDia as string;
    string muchodias = ViewBag.MuchosDias as string;
}

<h1>Edit</h1>

<h4>Cita</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID_Cita" />
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Pagado" /> @Html.DisplayNameFor(model => model.Pagado)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="Día" class="control-label"></label>
                <input asp-for="Día" class="form-control" />
                <span asp-validation-for="Día" class="text-danger"></span>
            </div>
            @if (!string.IsNullOrEmpty(diaerrorneo))
            {
                <div class="alert alert-danger">
                    @diaerrorneo
                </div>
            }
            @if (!string.IsNullOrEmpty(muchodias))
            {
                <div class="alert alert-danger">
                    @muchodias
                </div>
            }
            <div class="form-group">
                <label asp-for="Hora" class="control-label"></label>
                <input asp-for="Hora" class="form-control" />
                <span asp-validation-for="Hora" class="text-danger"></span>
            </div>
            @if (!string.IsNullOrEmpty(errorMensaje))
            {
                <div class="alert alert-danger">
                    @errorMensaje
                </div>
            }
            <div class="form-group">
                <label asp-for="ID_Doctor" class="control-label"></label>
                <select asp-for="ID_Doctor" class="form-control" asp-items="ViewBag.ID_Doctor"></select>
                <span asp-validation-for="ID_Doctor" class="text-danger"></span>
            </div>
           @* <div class="form-group">
                <label asp-for="ID_Receta_Medica" class="control-label"></label>
                <select asp-for="ID_Receta_Medica" class="form-control" asp-items="ViewBag.ID_Receta_Medica"></select>
                <span asp-validation-for="ID_Receta_Medica" class="text-danger"></span>
            </div>*@
            <div class="form-group">
                <label asp-for="ID_Paciente" class="control-label"></label>
                <select asp-for="ID_Paciente" class="form-control" asp-items="ViewBag.ID_Paciente"></select>
                <span asp-validation-for="ID_Paciente" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Hospital/Views/Citas/Index.cshtml
@model IEnumerable<Hospital.Models.Cita>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Pagado)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Día)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Hora)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Doctor)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Receta_Medica)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Paciente)
            </th>
            <th>
                Especialidad
            </th>
            <th>
                Consultorio
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Pagado)
            </td>
            <td>
                    @item.Día.ToString("dd/MM/yyyy")
                   @* @Html.DisplayFor(modelItem => item.Día)*@
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Hora)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Doctor.Usuario.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Receta_Medica.Especificaciones)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Paciente.Usuario.Nombre)
            </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Doctor.Especialidad.Nombre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Doctor.Consultorio.Nombre)
                </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.ID_Cita">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.ID_Cita">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.ID_Cita">Delete</a> |
                <a asp-action="CreateCita" asp-controller="Receta_Medica" asp-route-id="@item.ID_Cita">Agegar Receta</a>
            </td>
        </tr>
}
    </tbody>
</table>

Hospital/Views/Citas/IndexDoctor.cshtml
@model IEnumerable<Hospital.Models.Cita>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Pagado)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Día)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Hora)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Doctor)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Receta_Medica)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Paciente)
            </th>
            <th>
                Especialidad
            </th>
            <th>
                Consultorio
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Pagado)
                </td>
                <td>
                    @item.Día.ToString("dd/MM/yyyy")
                    @* @Html.DisplayFor(modelItem => item.Día)*@
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Hora)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Doctor.Usuario.Nombre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Receta_Medica.Especificaciones)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Paciente.Usuario.Nombre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Doctor.Especialidad.Nombre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Doctor.Consultorio.Nombre)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.ID_Cita">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.ID_Cita">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.ID_Cita">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

Hospital/Views/Citas/IndexPaciente.cshtml
@model IEnumerable<Hospital.Models.Cita>

@{
    ViewData["Title"] = "IndexPaciente";
}

<h1>IndexPaciente</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Pagado)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Día)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Hora)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Doctor)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Paciente)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Pagado)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Día)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Hora)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Doctor.Usuario.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Paciente.Usuario.Nombre)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.ID_Cita">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.ID_Cita">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.ID_Cita">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>